create type "public"."medical_benefit_payment_type" as enum ('advance', 'reimburse');

create type "public"."medical_benefits_for" as enum ('self', 'spouse', 'parents', 'siblings', 'children');

create type "public"."medical_categories" as enum ('surgery_and_hospitalization', 'maternity_care', 'dental_care', 'vision_care', 'prescription_medicine', 'labs_and_medical_tests', 'consultation');


  create table "public"."employee_medical_limits" (
    "id" bigint generated by default as identity not null,
    "employee_id" uuid not null default gen_random_uuid(),
    "year" smallint not null,
    "limit" smallint not null,
    "remaining" smallint not null,
    "medical_category" public.medical_categories not null,
    "updated_at" timestamp with time zone not null,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
      );


alter table "public"."employee_medical_limits" enable row level security;


  create table "public"."medical_benefit_records" (
    "id" uuid not null default gen_random_uuid(),
    "employee_id" uuid not null default gen_random_uuid(),
    "date" date not null,
    "for" public.medical_benefits_for not null,
    "medical_category" public.medical_categories not null,
    "description" text not null,
    "cost_pkr" smallint not null,
    "reciept" character varying not null,
    "paid" boolean not null default false,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null,
    "deleted_at" timestamp with time zone,
    "payment_type" public.medical_benefit_payment_type not null default 'reimburse'::public.medical_benefit_payment_type
      );


alter table "public"."medical_benefit_records" enable row level security;


  create table "public"."medical_category_limits" (
    "id" uuid not null default gen_random_uuid(),
    "medical_category" public.medical_categories not null,
    "limit" smallint not null,
    "updated_at" timestamp with time zone not null,
    "deleted_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."medical_category_limits" enable row level security;

alter table "public"."leave_requests" disable row level security;

CREATE UNIQUE INDEX employee_medical_limits_pkey ON public.employee_medical_limits USING btree (id);

CREATE UNIQUE INDEX medical_benefit_records_pkey ON public.medical_benefit_records USING btree (id);

CREATE UNIQUE INDEX medical_category_limits_pkey ON public.medical_category_limits USING btree (id);

alter table "public"."employee_medical_limits" add constraint "employee_medical_limits_pkey" PRIMARY KEY using index "employee_medical_limits_pkey";

alter table "public"."medical_benefit_records" add constraint "medical_benefit_records_pkey" PRIMARY KEY using index "medical_benefit_records_pkey";

alter table "public"."medical_category_limits" add constraint "medical_category_limits_pkey" PRIMARY KEY using index "medical_category_limits_pkey";

alter table "public"."employee_medical_limits" add constraint "employee_medical_limits_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES public.employees(id) not valid;

alter table "public"."employee_medical_limits" validate constraint "employee_medical_limits_employee_id_fkey";

alter table "public"."medical_benefit_records" add constraint "medical_benefit_records_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES public.employees(id) not valid;

alter table "public"."medical_benefit_records" validate constraint "medical_benefit_records_employee_id_fkey";

grant delete on table "public"."employee_medical_limits" to "anon";

grant insert on table "public"."employee_medical_limits" to "anon";

grant references on table "public"."employee_medical_limits" to "anon";

grant select on table "public"."employee_medical_limits" to "anon";

grant trigger on table "public"."employee_medical_limits" to "anon";

grant truncate on table "public"."employee_medical_limits" to "anon";

grant update on table "public"."employee_medical_limits" to "anon";

grant delete on table "public"."employee_medical_limits" to "authenticated";

grant insert on table "public"."employee_medical_limits" to "authenticated";

grant references on table "public"."employee_medical_limits" to "authenticated";

grant select on table "public"."employee_medical_limits" to "authenticated";

grant trigger on table "public"."employee_medical_limits" to "authenticated";

grant truncate on table "public"."employee_medical_limits" to "authenticated";

grant update on table "public"."employee_medical_limits" to "authenticated";

grant delete on table "public"."employee_medical_limits" to "service_role";

grant insert on table "public"."employee_medical_limits" to "service_role";

grant references on table "public"."employee_medical_limits" to "service_role";

grant select on table "public"."employee_medical_limits" to "service_role";

grant trigger on table "public"."employee_medical_limits" to "service_role";

grant truncate on table "public"."employee_medical_limits" to "service_role";

grant update on table "public"."employee_medical_limits" to "service_role";

grant delete on table "public"."medical_benefit_records" to "anon";

grant insert on table "public"."medical_benefit_records" to "anon";

grant references on table "public"."medical_benefit_records" to "anon";

grant select on table "public"."medical_benefit_records" to "anon";

grant trigger on table "public"."medical_benefit_records" to "anon";

grant truncate on table "public"."medical_benefit_records" to "anon";

grant update on table "public"."medical_benefit_records" to "anon";

grant delete on table "public"."medical_benefit_records" to "authenticated";

grant insert on table "public"."medical_benefit_records" to "authenticated";

grant references on table "public"."medical_benefit_records" to "authenticated";

grant select on table "public"."medical_benefit_records" to "authenticated";

grant trigger on table "public"."medical_benefit_records" to "authenticated";

grant truncate on table "public"."medical_benefit_records" to "authenticated";

grant update on table "public"."medical_benefit_records" to "authenticated";

grant delete on table "public"."medical_benefit_records" to "service_role";

grant insert on table "public"."medical_benefit_records" to "service_role";

grant references on table "public"."medical_benefit_records" to "service_role";

grant select on table "public"."medical_benefit_records" to "service_role";

grant trigger on table "public"."medical_benefit_records" to "service_role";

grant truncate on table "public"."medical_benefit_records" to "service_role";

grant update on table "public"."medical_benefit_records" to "service_role";

grant delete on table "public"."medical_category_limits" to "anon";

grant insert on table "public"."medical_category_limits" to "anon";

grant references on table "public"."medical_category_limits" to "anon";

grant select on table "public"."medical_category_limits" to "anon";

grant trigger on table "public"."medical_category_limits" to "anon";

grant truncate on table "public"."medical_category_limits" to "anon";

grant update on table "public"."medical_category_limits" to "anon";

grant delete on table "public"."medical_category_limits" to "authenticated";

grant insert on table "public"."medical_category_limits" to "authenticated";

grant references on table "public"."medical_category_limits" to "authenticated";

grant select on table "public"."medical_category_limits" to "authenticated";

grant trigger on table "public"."medical_category_limits" to "authenticated";

grant truncate on table "public"."medical_category_limits" to "authenticated";

grant update on table "public"."medical_category_limits" to "authenticated";

grant delete on table "public"."medical_category_limits" to "service_role";

grant insert on table "public"."medical_category_limits" to "service_role";

grant references on table "public"."medical_category_limits" to "service_role";

grant select on table "public"."medical_category_limits" to "service_role";

grant trigger on table "public"."medical_category_limits" to "service_role";

grant truncate on table "public"."medical_category_limits" to "service_role";

grant update on table "public"."medical_category_limits" to "service_role";


